language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"

before_script:
  - npm install
  - mysql -e 'create database yodel_test;'
  - cp config/knexfile.sample.js config/knexfile.js
  - NODE_ENV=test tasks/migrate

services:
  - redis-server
